POST http://localhost:3002/api/patients
Content-Type: application/json

{
  "name": "jihhsssuu",
  "dateOfBirth": "2014-04-21",
  "ssn": "327212-3822",
  "gender": "female",
  "occupation": "blehhhhh",
  "entries": [{"id": "b4f4eca1-2aa7-4b13-9a18-4a5535c3c8da",
    "date": "2019-10-20",
    "specialist": "MD House",
    "type": "HealthCheck",
    "description": "Yearly control visit. Cholesterol levels back to normal.",
    "healthCheckRating": 0
   }]
}