POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "jihhsssuu",
  "dateOfBirth": "2014-04-21",
  "ssn": "327212-3822",
  "gender": "kjehehhhh",
  "occupation": "blehhhhh"
}